// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertNaming(arg1) {
  return window['go']['main']['App']['ConvertNaming'](arg1);
}

export function ExecuteRename(arg1) {
  return window['go']['main']['App']['ExecuteRename'](arg1);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function GetOutputDir() {
  return window['go']['main']['App']['GetOutputDir']();
}

export function GetTypes() {
  return window['go']['main']['App']['GetTypes']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SetModules(arg1) {
  return window['go']['main']['App']['SetModules'](arg1);
}

export function SetOutputDir(arg1) {
  return window['go']['main']['App']['SetOutputDir'](arg1);
}

export function SetTypes(arg1) {
  return window['go']['main']['App']['SetTypes'](arg1);
}

export function UpdateItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateItem'](arg1, arg2, arg3, arg4);
}
