// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertNaming(arg1:string):Promise<main.NamingResult>;

export function ExecuteRename(arg1:Array<main.ImageItem>):Promise<string>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetModules():Promise<Array<string>>;

export function GetOutputDir():Promise<string>;

export function GetTypes():Promise<Array<string>>;

export function SaveDroppedFile(arg1:string,arg2:string):Promise<string>;

export function SelectFiles():Promise<Array<main.ImageItem>>;

export function SelectFolder():Promise<Array<main.ImageItem>>;

export function SelectOutputDir():Promise<string>;

export function SetModules(arg1:Array<string>):Promise<void>;

export function SetOutputDir(arg1:string):Promise<void>;

export function SetTypes(arg1:Array<string>):Promise<void>;

export function UpdateItem(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
